stages:
  fetch:
    cmd: poetry run python src/data/fetch_data.py
    deps:
      - src/data/fetch_data.py
    outs:
      - data/raw:
          persist: true
  preprocess_and_combine:

  preprocess:
    cmd: poetry run python src/data/preprocess_data.py
    deps:
      - src/data/preprocess_data.py
      - data/raw
    outs:
      - data/processed/mbajk:
          persist: true
      - data/processed/weather:
          persist: true
      - data/processed/combined:
          persist: true

  split:
    cmd: poetry run python src/data/final_processing.py
    deps:
      - src/data/final_processing.py
      - data/processed/combined
    outs:
      - data/processed/train:
          persist: true
      - data/processed/test:
          persist: true
