stages:
  fetch_data:
    cmd: python src/data/fetch_data.py
    deps:
      - src/data/fetch_data.py
    outs:
      - data/raw
  preprocess_and_combine:
    cmd: python src/data/preprocess_data.py
    deps:
      - data/raw
      - src/data/preprocess_data.py
    outs:
      - data/processed/combined
      - data/processed/mbajk
      - data/processed/weather
  validate_data:
    cmd: python src/data/validate_data.py
    deps:
      - data/processed/combined/current_data.csv
      - src/data/validate_data.py
    outs:
      - reports/validation_report.html
  test_data:
    cmd: python src/data/test_data.py
    deps:
      - data/processed/combined/current_data.csv
      - data/reference/reference_data.csv
      - src/data/test_data.py
    outs:
      - reports/test_report.html
  kolmogorov_smirnov_test:
    cmd: python src/data/kolmogorov_smirnov_test.py
    deps:
      - data/processed/combined/current_data.csv
      - data/reference/reference_data.csv
      - src/data/kolmogorov_smirnov_test.py
  final_processing:
    cmd: python src/data/final_processing.py
    deps:
      - data/processed/combined
      - src/data/final_processing.py
    outs:
      - data/processed/train
      - data/processed/test
  train_model:
    cmd: python src/data/train_model.py
    deps:
      - data/processed/train
      - src/data/train_model.py
    outs:
      - models
  predict_model:
    cmd: python src/data/predict_model.py
    deps:
      - data/processed/test
      - src/data/predict_model.py
      - models
    outs:
      - reports/test