stages:
  fetch:
    cmd: poetry run python src/data/fetch_data.py
    deps:
      - src/data/fetch_data.py
    outs:
      - data/raw:
          persist: true

  preprocess:
    cmd: poetry run python src/data/preprocess_data.py
    deps:
      - src/data/preprocess_data.py
      - data/raw
    outs:
      - data/processed/mbajk:
          persist: true
      - data/processed/weather:
          persist: true
      - data/processed/combined:
          persist: true

  split:
    cmd: poetry run python src/data/final_processing.py
    deps:
      - src/data/final_processing.py
      - data/processed/combined
    outs:
      - data/processed/train:
          persist: true
      - data/processed/test:
          persist: true
  
  reference_data:
    cmd: |
      mkdir -p data/processed
      cp -r data/processed/combined data/processed/reference_data
      cp -r data/processed/combined data/processed/current_data
    deps:
      - data/processed/combined
    outs:
      - data/processed/reference_data
      - data/processed/current_data

  validate_and_test:
    cmd: poetry run python src/data/validate_and_test.py
    deps:
        - src/data/validate_and_test.py
        - data/processed/reference_data
        - data/processed/current_data

  split_data:
    cmd: poetry run python src/data/split_data.py
    deps:
      - src/data/split_data.py
      - data/processed/current_data
    outs:
      - data/processed/train_test_from_current/train:
          persist: true
      - data/processed/train_test_from_current/test:
          persist: true

  train_model_mlflow:
    cmd: poetry run python src/models/train_model_mlflow.py
    deps:
      - src/models/train_model_mlflow.py
      - data/processed/train_test_from_current/train
    outs:
      - models/models_mlflow:
          persist: true

  predict_model_mlflow:
    cmd: poetry run python src/models/predict_model_mlflow.py
    deps:
      - src/models/predict_model_mlflow.py
      - models/models_mlflow
      - data/processed/train_test_from_current/test
  
  merge_data:
    cmd: poetry run python src/data/merge_data.py
    deps:
      - src/data/merge_data.py
      - data/processed/combined
    outs:
      - data/processed/merged/data.csv:
          persist: true

  reference_data_merged:
    cmd: |
      cp data/processed/merged/data.csv data/processed/merged/reference_data.csv
      cp data/processed/merged/data.csv data/processed/merged/current_data.csv
    deps:
      - data/processed/merged/data.csv
    outs:
      - data/processed/merged/reference_data.csv
      - data/processed/merged/current_data.csv

  validate_and_test_merged:
    cmd: poetry run python src/data/validate_and_test_merged.py
    deps:
      - src/data/validate_and_test_merged.py
      - data/processed/merged/reference_data.csv
      - data/processed/merged/current_data.csv
  
  split_data_merged:
    cmd: poetry run python src/data/split_merged_data.py
    deps:
      - src/data/split_merged_data.py
      - data/processed/merged/current_data.csv
    outs:
      - data/processed/train_test_merged/train.csv:
          persist: true
      - data/processed/train_test_merged/test.csv:
          persist: true

  train_model_full_mlflow:
    cmd: poetry run python src/models/train_full_model_mlflow.py
    deps:
      - src/models/train_full_model_mlflow.py
      - data/processed/train_test_merged/train.csv
      - data/processed/train_test_merged/test.csv
    outs:
      - models/models_mlflow_full:
          persist: true