stages:
  fetch:
    cmd: poetry run python src/data/fetch_data.py
    deps:
      - src/data/fetch_data.py
    outs:
      - data/raw:
          persist: true

  preprocess:
    cmd: poetry run python src/data/preprocess_data.py
    deps:
      - src/data/preprocess_data.py
      - data/raw
    outs:
      - data/processed/mbajk:
          persist: true
      - data/processed/weather:
          persist: true
      - data/processed/combined:
          persist: true

  reference_data_merged:
    cmd: |
      dvc checkout data/processed/combined/data.csv
      cp data/processed/combined/data.csv data/processed/reference_data.csv
      dvc pull
      cp data/processed/combined/data.csv data/processed/current_data.csv
    deps:
      - data/processed/combined/data.csv
    outs:
      - data/processed/reference_data.csv
      - data/processed/current_data.csv

  split:
    cmd: poetry run python src/data/final_processing.py
    deps:
      - src/data/final_processing.py
      - data/processed/combined
    outs:
      - data/processed/train:
          persist: true
      - data/processed/test:
          persist: true
  
  reference_data:
    cmd: |
      dvc checkout data/processed/combined
      cp -r data/processed/combined data/processed/reference_data
      dvc pull
      cp -r data/processed/combined data/processed/current_data
    deps:
      - data/processed/combined
    outs:
      - data/processed/reference_data
      - data/processed/current_data

  validate_and_test:
    cmd: poetry run python src/data/validate_and_test.py
    deps:
        - src/data/validate_and_test.py
        - data/processed/reference_data
        - data/processed/current_data
  
  split_data:
    cmd: poetry run python src/data/split_data.py
    deps:
      - src/data/split_data.py
      - data/processed/current_data
    outs:
      - data/processed/train_test_from_current/train:
          persist: true
      - data/processed/train_test_from_current/test:
          persist: true

  train_model_mlflow:
    cmd: poetry run python src/models/train_model_mlflow.py
    deps:
      - src/models/train_model_mlflow.py
      - data/processed/train_test_from_current/train
    outs:
      - models/models_mlflow:
          persist: true

  predict_model_mlflow:
    cmd: poetry run python src/models/predict_model_mlflow.py
    deps:
      - src/models/predict_model_mlflow.py
      - models/models_mlflow
      - data/processed/train_test_from_current/test