name: Build and Deploy Backend & Frontend to Koyeb

on:
  push:
    branches:
      - main  # Change to the branch that triggers deployment

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Backend Docker image (AMD64)
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            -t xopiie/mbajk-backend:latest \
            -t xopiie/mbajk-backend:v04 \
            --push .

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Frontend Docker image (AMD64)
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            -t xopiie/mbajk-frontend:latest \
            -t xopiie/mbajk-frontend:v04 \
            --push .

  deploy-to-koyeb:
    needs: [build-and-push-backend, build-and-push-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend to Koyeb
        run: |
          curl -X POST "https://app.koyeb.com/v1/services/mbajk-backend/deploy" \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"image": "xopiie/mbajk-backend:v04"}'

      - name: Deploy Frontend to Koyeb
        run: |
          curl -X POST "https://app.koyeb.com/v1/services/mbajk-frontend/deploy" \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"image": "xopiie/mbajk-frontend:v04"}'
