name: 'Data Pipeline'

on:
  schedule:
    - cron: '15 * * * *' # Runs every hour at 15 minutes past the hour
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  process_data:
    runs-on: ubuntu-latest
    
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      # ✅ 1. Preveri kodo iz GitHub repozitorija
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ 2. Nastavi Python okolje
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # ✅ 3. Namesti potrebne odvisnosti
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry dvc[all]
          poetry install

      # ✅ 4. Nastavi DVC povezavo do DagsHub
      - name: Configure DagsHub credentials
        run: |
          dvc remote modify dagshub_remote --local auth basic
          dvc remote modify dagshub_remote --local user NadicaUzunova
          dvc remote modify dagshub_remote --local password ${{ secrets.DAGSHUB_TOKEN }}

      # ✅ 5. Prenesi podatke z DVC
      - name: Pull DVC data
        run: dvc pull

      # ✅ 6. Izvedi DVC pipeline
      - name: Reproduce DVC pipeline (force)
        run: dvc repro --force

      # ✅ 7. Pošlji spremembe, če obstajajo
      - name: Commit and push if there are changes
        env:
          mbajkML: ${{ secrets.mbajkML }}
        run: |
          git config --global user.email "nadica.uzunova@student.um.si"
          git config --global user.name "NadicaUzunova"
          git remote set-url origin https://x-access-token:${mbajkML}@github.com/NadicaUzunova/mbajkML.git
          git add .
          git commit -m "Update data" || echo "No changes to commit"
          git push origin main

      # ✅ 8. Pošlji podatke nazaj v DVC
      - name: Push DVC changes
        run: dvc push