name: 'Fetch and Process Data'

on:
  schedule:
    - cron: '15 * * * *'  # Runs every hour at 15 minutes past the hour
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.7

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run data processing script
      - name: Run processing script
        run: python src/data/script.py

      # Step 5: Commit and push changes if any
      - name: Commit and push if there are changes
        run: |
          git config user.email "nadica.uzunova@student.um.si"
          git config user.name "NadicaUzunova"
          git add .
          git commit -m "Update data" || echo "No changes to commit"
          git push
          
  test_and_fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc pytest

      - name: Run API Tests
        run: pytest tests/

      - name: Run DVC Pipeline
        run: dvc repro

      - name: Push to DVC Remote
        run: dvc push