name: 'Fetch and Process Data'

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.7

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Step 4: Run tests
      - name: Run tests
        run: poetry run pytest ./src/tests/

      - name: Fetch data
        run: python ./src/data/fetch_data.py

      - name: Preprocess data
        run: python ./src/data/preprocess_data.py

      - name: Final processing
        run: python ./src/data/final_processing.py

      - name: Commit and push if there are changes
        run: |
          git config user.email "nadica.uzunova@student.um.si"
          git config user.name "NadicaUzunova"
          git add .
          git commit -m "Update data" || echo "No changes to commit"
          git push