# name: 'Tests'
# on:
#   push:
#     branches: [main]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Python setup (3.11.7)
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.11.7
#       - name: Install dependencies
#         run: |
#           pip install poetry
#           poetry install --no-root
#       - name: API tests
#         run: poetry run pytest