name: 'Tests'

on:
  push:
    branches: [main]  # Run on push to the main branch
  pull_request:       # Run on pull requests to main
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python (3.11.7)
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.7

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      # Step 4: Run tests
      - name: Run tests
        run: poetry run pytest tests/